[package]
name = "awsm-env"
description = "A lightweight utility for syncing AWS Secrets Manager secrets to environment variables."
version = "0.0.2"
edition = "2024"
homepage = "https://github.com/affanshahid/awsm-env"
documentation = "https://docs.rs/awsm-env"
repository = "https://github.com/affanshahid/awsm-env"
readme = "README.md"
license = "MIT"
keywords = ["aws-secrets-manager", "env", "environment_variable"]

[dependencies]
indexmap = "2.8.0"
pest = "2.8.0"
pest_derive = "2.8.0"
thiserror = "2.0.12"
